### PR TITLE
Simultaneous python 2 and python 3 support

### PR DESCRIPTION
**Pull request by henrygab**

### CODE REVIEW

**Comment by henrygab** [comment]
@blainebauer -- If you're not interested in maintaining this, let me know?.

**Comment by blainebauer** [comment]
It was a small project I did while learning python, I'm probably not going to be spending time on it anymore.
    On Sunday, September 29, 2019, 01:27:07 PM PDT, Henry Gabryjelski <notifications@github.com> wrote:  
 
 
@blainebauer -- If you're not interested in maintaining this, let me know?.

**Comment by henrygab** [comment]
@blainebauer -- OK, thanks for the quick response.  Two final questions:

1. What license can I use your code be under?  (e.g., I would prefer either it having been dedicated to the "Public Domain", or use of the "MIT" license ... no GPL please, as it prevents code use in many environments.)

2. Would you be willing to "transfer" this repo?  I ask because there are links to this repo (e.g., in Silicondust forums), and it'd be nice to have the links auto-forward to the latest version.  See https://help.github.com/en/articles/transferring-a-repository for how it'd work.

**Comment by blainebauer** [comment]
Sure, I'll transfer it (I'll need your username). Anyway public domain is fine.
    On Sunday, September 29, 2019, 03:04:46 PM PDT, Henry Gabryjelski <notifications@github.com> wrote:  
 
 
@blainebauer -- OK, thanks for the quick response. Two final questions:
   
   -    
What license can I use your code be under? (e.g., I would prefer either it having been dedicated to the "Public Domain", or use of the "MIT" license ... no GPL please, as it prevents code use in many environments.)

   -    
Would you be willing to "transfer" this repo? I ask because there are links to this repo (e.g., in Silicondust forums), and it'd be nice to have the links auto-forward to the latest version. See https://help.github.com/en/articles/transferring-a-repository for how it'd work.

**Comment by henrygab** [comment]
of course!  my username is '**henrygab**'.  thanks!

**Comment by blainebauer** [comment]
It's all yours


    On Monday, September 30, 2019, 07:46:20 AM PDT, Henry Gabryjelski <notifications@github.com> wrote:  
 
 
of course! my username is 'henrygab'. thanks!

**Comment by henrygab** [comment]
Hmmm, still no email on this.  Did you go through the [six steps](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) listed on the GitHub page?

Summarized:
1. On GitHub, navigate to the main page of the repository.
2. Under your repository name, click Settings. 
3. Under "Danger Zone", click Transfer. 
4. Read the info, then type the name of the user ('henrygab') you'd like to transfer ownership of the repository to.
5. Read the warnings
6. Type the name of the repository you'd like to transfer, then click I understand, transfer this repository. 

This should generate an email to me, and then I will have 24 hours to complete the transfer.  I'm sorry this is so involved... it's just referenced on silicon dust forums, so I'd like to avoid interested users getting 404 errors, and instead get redirected to where this can live on (with updates).  Thanks!

**Comment by blainebauer** [comment]
Yes, I did those steps. It says "the repository is being transferred"...I'm not sure how long it should take.
    On Monday, September 30, 2019, 11:37:41 PM PDT, Henry Gabryjelski <notifications@github.com> wrote:  
 
 
Hmmm, still no email on this. Did you go through the six steps listed on the GitHub page?

Summarized:
   
   - On GitHub, navigate to the main page of the repository.
   - Under your repository name, click Settings.
   - Under "Danger Zone", click Transfer.
   - Read the info, then type the name of the user ('henrygab') you'd like to transfer ownership of the repository to.
   - Read the warnings
   - Type the name of the repository you'd like to transfer, then click I understand, transfer this repository.

This should generate an email to me, and then I will have 24 hours to complete the transfer. I'm sorry this is so involved... it's just referenced on silicon dust forums, so I'd like to avoid interested users getting 404 errors, and instead get redirected to where this can live on (with updates). Thanks!

**Comment by henrygab** [comment]
Mea culpa!  It was there all along, I just missed it.  All transferred now.  Thanks!

**Pull request closed without merging**
